name       : feh
version    : 3.1.2
release    : 28
homepage   : https://feh.finalrewind.org/
source     :
    - git|https://github.com/derf/feh.git : 3.1.2
license    : MIT-feh
component  : multimedia.graphics
summary    : feh is an X11 image viewer aimed mostly at console users.
description: |
    feh is an X11 image viewer aimed mostly at console users. Unlike most other viewers, it does not have a fancy GUI, but simply displays images. It is controlled via commandline arguments and configurable key/mouse actions.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(imlib2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(xinerama)
    - pkgconfig(xt)
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
