name       : feh
version    : '2.23'
release    : 15
homepage   : https://feh.finalrewind.org/
source     :
    - https://feh.finalrewind.org/feh-2.23.tar.bz2 : 16df3cb813526a549e854aa82f80bcb299b9e83dd687ab4216a84e86f61722a1
license    : MIT
component  : multimedia.graphics
summary    : feh is an X11 image viewer aimed mostly at console users.
description: |
    feh is an X11 image viewer aimed mostly at console users. Unlike most other viewers, it does not have a fancy GUI, but simply displays images. It is controlled via commandline arguments and configurable key/mouse actions.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(imlib2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(x11)
    - pkgconfig(xinerama)
    - pkgconfig(xt)
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
