name       : feh
version    : '2.19'
release    : 9
homepage   : https://feh.finalrewind.org/
source     :
    - https://feh.finalrewind.org/feh-2.19.tar.bz2 : cebe25d8393a07aa79a6b2f99beb133d8de0cbc00d46bccc4df276248cc9d0e9
license    : MIT
component  : multimedia.graphics
summary    : feh is an X11 image viewer aimed mostly at console users.
description: |
    feh is an X11 image viewer aimed mostly at console users. Unlike most other viewers, it does not have a fancy GUI, but simply displays images. It is controlled via commandline arguments and configurable key/mouse actions.
builddeps  :
    - pkgconfig(imlib2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(x11)
    - pkgconfig(xinerama)
    - pkgconfig(xt)
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
