name       : feh
version    : '3.3'
release    : 31
homepage   : https://feh.finalrewind.org/
source     :
    - git|https://github.com/derf/feh.git : 3.3
license    : MIT
component  : multimedia.graphics
summary    : feh is an X11 image viewer aimed mostly at console users.
description: |
    feh is an X11 image viewer aimed mostly at console users. Unlike most other viewers, it does not have a fancy GUI, but simply displays images. It is controlled via commandline arguments and configurable key/mouse actions.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(imlib2)
    - pkgconfig(libcurl)
    - pkgconfig(libexif)
    - pkgconfig(libpng)
    - pkgconfig(xinerama)
    - pkgconfig(xt)
build      : |
    %make PREFIX=/usr app=1 exif=1 inotify=1
install    : |
    %make_install PREFIX=/usr
