name       : feh
version    : '2.25'
release    : 18
homepage   : https://feh.finalrewind.org/
source     :
    - https://github.com/derf/feh/archive/2.25.tar.gz : 1003569c5001de5f9e7beda95f54ce1745cc3e10a0310962996c39aeea3b87fa
license    : MIT
component  : multimedia.graphics
summary    : feh is an X11 image viewer aimed mostly at console users.
description: |
    feh is an X11 image viewer aimed mostly at console users. Unlike most other viewers, it does not have a fancy GUI, but simply displays images. It is controlled via commandline arguments and configurable key/mouse actions.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(imlib2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(x11)
    - pkgconfig(xinerama)
    - pkgconfig(xt)
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
