name       : feh
version    : '3.0'
release    : 26
homepage   : https://feh.finalrewind.org/
source     :
    - https://github.com/derf/feh/archive/3.0.tar.gz : 793bf29cdf23ffe50c7c99552cb0141958317acc52babe153d3203cb34092e5e
license    : MIT-feh
component  : multimedia.graphics
summary    : feh is an X11 image viewer aimed mostly at console users.
description: |
    feh is an X11 image viewer aimed mostly at console users. Unlike most other viewers, it does not have a fancy GUI, but simply displays images. It is controlled via commandline arguments and configurable key/mouse actions.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(imlib2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(x11)
    - pkgconfig(xinerama)
    - pkgconfig(xt)
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
