name       : feh
version    : 2.14.2
release    : 1
homepage   : https://feh.finalrewind.org/
source     :
    - http://feh.finalrewind.org/feh-2.14.2.tar.bz2 : c80f3d3297b3b6ee4898572d19692f5e19eb3066a9ca078c3099d39004a7e0cf
license    : MIT
summary    : feh is an X11 image viewer aimed mostly at console users.
description: |
    feh is an X11 image viewer aimed mostly at console users. Unlike most other viewers, it does not have a fancy GUI, but simply displays images. It is controlled via commandline arguments and configurable key/mouse actions.
builddeps  :
    - pkgconfig(imlib2)
    - pkgconfig(libpng)
    - pkgconfig(x11)
    - pkgconfig(xinerama)
    - pkgconfig(xt)
build      : |
    %make
install    : |
    %make_install
